name: r5
access_mode: remote_direct_restricted
advertise_host: 3.12.221.9
bind_host: 0.0.0.0
db_bind_host: 0.0.0.0
allow_public_web_bind: true
allow_public_db_bind: true
trusted_operator_cidrs:
  - 0.0.0.0/0
ssh_user: ubuntu
compose_dir_remote: /home/ubuntu
compose_file_remote: /home/ubuntu/docker-compose.yml
security_group_id: sg-08792057943b27a65
region: us-east-2
