"""Host-owned adversarial action contracts and reward compilation."""

from worldsim.adversarial_actions.benign_action_contracts import (
    apply_benign_action_contract,
    apply_phase2_tier3_benign_action_contract,
    benign_action_witness,
    card_benign_action_evidence_stage,
    card_requires_benign_action_evidence,
    card_requires_phase2_tier3_benign_action_evidence,
    validate_benign_action_evidence_stage,
)
from worldsim.adversarial_actions.capability_adapters import (
    CAPABILITY_ADAPTER_VERSION,
    CapabilityTaskAdapter,
    available_capability_adapter_profiles,
    capability_adapters_for_profile,
)
from worldsim.adversarial_actions.capability_contracts import (
    ACTION_CAPABILITY_CONTRACTS,
    ActionCapabilityContract,
    action_kind_compatible_with_task,
    action_kind_compatible_with_task_card,
    action_kinds_for_capability_family,
    capability_family_from_task,
    capability_family_from_task_card,
    compatibility_reason_for_task_card,
    compatible_action_kinds_from_task,
    describe_action_capability,
    get_action_capability_contract,
)
from worldsim.adversarial_actions.catalog import (
    ACTION_SPECS,
    ActionSpec,
    describe_action_kind,
    get_action_spec,
)
from worldsim.adversarial_actions.compiler import (
    ACTION_KINDS,
    ACTION_POLICIES,
    ACTION_SIGNAL_BY_KIND,
    action_metadata_for_task,
    allowed_action_options,
    annotate_exposure_contracts_with_action_policy,
    annotate_exposure_contracts_with_actions,
    canonical_action_policy,
    compile_adversarial_final_state_check,
    compile_adversarial_reward,
    reward_signal_for_task,
)
from worldsim.adversarial_actions.payload_guidance import (
    action_payload_guidance_text,
    action_payload_preservation_error,
    action_payload_preservation_report,
    build_action_payload_guidance,
)
from worldsim.adversarial_actions.readiness import build_action_readiness_artifacts
from worldsim.adversarial_actions.tier3 import (
    TIER3_ADAPTER_SPECS,
    TIER3_MATURITY_LEVELS,
    action_kinds_for_exposure_contracts,
)

__all__ = [
    "ACTION_CAPABILITY_CONTRACTS",
    "ACTION_KINDS",
    "ACTION_POLICIES",
    "ACTION_SIGNAL_BY_KIND",
    "ACTION_SPECS",
    "CAPABILITY_ADAPTER_VERSION",
    "TIER3_ADAPTER_SPECS",
    "TIER3_MATURITY_LEVELS",
    "ActionCapabilityContract",
    "ActionSpec",
    "CapabilityTaskAdapter",
    "action_kind_compatible_with_task",
    "action_kind_compatible_with_task_card",
    "action_kinds_for_capability_family",
    "action_kinds_for_exposure_contracts",
    "action_metadata_for_task",
    "action_payload_guidance_text",
    "action_payload_preservation_error",
    "action_payload_preservation_report",
    "allowed_action_options",
    "annotate_exposure_contracts_with_action_policy",
    "annotate_exposure_contracts_with_actions",
    "apply_benign_action_contract",
    "apply_phase2_tier3_benign_action_contract",
    "available_capability_adapter_profiles",
    "benign_action_witness",
    "build_action_payload_guidance",
    "build_action_readiness_artifacts",
    "canonical_action_policy",
    "capability_adapters_for_profile",
    "capability_family_from_task",
    "capability_family_from_task_card",
    "card_benign_action_evidence_stage",
    "card_requires_benign_action_evidence",
    "card_requires_phase2_tier3_benign_action_evidence",
    "compatibility_reason_for_task_card",
    "compatible_action_kinds_from_task",
    "compile_adversarial_final_state_check",
    "compile_adversarial_reward",
    "describe_action_capability",
    "describe_action_kind",
    "get_action_capability_contract",
    "get_action_spec",
    "reward_signal_for_task",
    "validate_benign_action_evidence_stage",
]
